title: How to code!?
description: Documenting things i learnt for future references.
theme: just-the-docs

url: https://wulcat.github.io

aux_links:
  Projects: http://wulcat.com
  Github: https://github.com/wulcat

livereload: true
